spring:
  jpa:
    hibernate:
      ddl-auto: ${DEPLOYER_DDL_AUTO:validate}
  datasource:
    url: jdbc:mysql://${DEPLOYER_DB_HOST}/${DEPLOYER_DB_NAME}?serverTimezone=UTC
    username: ${DEPLOYER_DB_USER}
    password: ${DEPLOYER_DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${DEPLOYER_KEYCLOAK_URI}


server:
  port: ${DEPLOYER_PORT:8080}
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  servlet:
    session:
      cookie:
        name: ${DEPLOYER_COOKIE_PREFIX:DEPLOYER}_JSESSIONID
        path: /
        domain: ${DEPLOYER_DOMAIN:localhost}

keycloak:
  auth-server-url: ${DEPLOYER_KEYCLOAK_URL}
  realm: ${DEPLOYER_KEYCLOAK_REALM}
  resource: ${DEPLOYER_KEYCLOAK_CLIENT}
  principal-attribute: preferred_username
  credentials:
    secret: ${DEPLOYER_KEYCLOAK_SECRET}

deployer:
  security:
    oauth-scope: ${DEPLOYER_SECURITY_OAUTH_SCOPE:litecd}
    include-client-roles: ${DEPLOYER_SECURITY_INCLUDE_CLIENT_ROLES:false}
    include-realm-roles: ${DEPLOYER_SECURITY_INCLUDE_REALM_ROLES:true}
    client-name: ${DEPLOYER_SECURITY_CLIENT_NAME:litecd}
    admin-role: ${DEPLOYER_SECURITY_ADMIN_ROLE:litecd_admin}
  max-file-size: ${DEPLOYER_STATIC_FILE_MAX_SIZE:100MB}
  filesystem-storage-path: ${DEPLOYER_FILESYSTEM_STORAGE_PATH:data}
  domain: ${DEPLOYER_DOMAIN:localhost:8080}
  protocol: ${DEPLOYER_PROTOCOL:https}

  allowed-port-range: ${DEPLOYER_PORT_RANGE:9500-10000}
  displayed-log-size: ${DEPLOYER_DISPLAYED_LOG_SIZE:500000}
